import type { NextPage } from "next";

import Head from "next/head";

import PokemonCard from "../components/PokemonCard";

const Home: NextPage = () => {
  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta content="Generated by create next app" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <section>
        <div className="grid grid-cols-3 mx-auto">
          <PokemonCard
            avatarUrl="https://storage.googleapis.com/indie-hackers.appspot.com/avatars/300x300_DUFTlhOdmSdoT9F4r1Woo40pyML2.webp"
            description="Free and Premium themes, UI Kit's, templates and landing pages built with Tailwind CSS, HTML & Next.js."
            name="Foo"
            type="grass"
          />

          <PokemonCard
            avatarUrl="https://storage.googleapis.com/indie-hackers.appspot.com/avatars/300x300_DUFTlhOdmSdoT9F4r1Woo40pyML2.webp"
            description="Free and Premium themes, UI Kit's, templates and landing pages built with Tailwind CSS, HTML & Next.js."
            name="Foo"
            type="grass"
          />

          <PokemonCard
            avatarUrl="https://storage.googleapis.com/indie-hackers.appspot.com/avatars/300x300_DUFTlhOdmSdoT9F4r1Woo40pyML2.webp"
            description="Free and Premium themes, UI Kit's, templates and landing pages built with Tailwind CSS, HTML & Next.js."
            name="Foo"
            type="grass"
          />
        </div>
      </section>

      <h1 className="text-3xl font-bold underline">Hello world!</h1>
    </div>
  );
};

export default Home;
